spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: elsprage-words
          uri: lb://elsprage-words
          predicates:
            - Path=/words/**, /languages/**, /packets/**
        - id: elsprage-users
          uri: lb://elsprage-users
          predicates:
            - Path=/users/**, /authentication/**
        - id: elsprage-learning
          uri: lb://elsprage-learning
          predicates:
            - Path=/learning/**, /games/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4200
              - http://localhost:8080
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH