spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: elsprage-words
          uri: lb://elsprage-words
          predicates:
            - Path=/words/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST